### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by rainabba**
Updated stats in the "Why?" section to further emphasize the point.

### CODE REVIEW

**Review by nelsonic — APPROVED** [review]
@rainabba thanks _very_ much for updating the stats in the readme! 🎉

**Comment by rainabba** [comment]
@nelsonic Not sure if that's *VERY* sincere, or just INTJ (saracastic), but you're welcome either way ;)

**Comment by rainabba** [comment]
Looking back at https://github.com/dwyl/hapi-auth-google/pull/41, I think I need to be less pessimistic and more gracious. Thanks for helping teach me!

**Comment by nelsonic** [comment]
@rainabba apologies if my gratitude appears sarcastic, 
I'm always amazed that people `make` time to contribute improvements to Open Source, 
readme improvements/updates are _especially good_ 
because they are the _first_ thing a `new` person sees 
when they are viewing a project/repository for the first time. 
The fact that you have taken time out of your day to create a PR
 is _awesome_! so I am _very_ grateful. 👍 
Thanks again! 🎉

**Pull request merged**
