### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by rainabba**
Updated Google user stats in README.md

### CODE REVIEW

**Review by nelsonic — APPROVED** [review]
@rainabba thanks very much for updating the stat and link. 👍

**Comment by nelsonic** [comment]
We need to update the test and/or environment variable on Travis-CI in order to merge this... 🙄

**Comment by rainabba** [comment]
Just to be clear, this isn't something I did right? If so, looks like I need some guidance on how to proceed :)

**Comment by nelsonic** [comment]
@rainabba not at all. what you did is _amaze_! thanks so much! 😍  🎉 
(_we need to update it on our side ..._) 🔨

**Comment by nelsonic** [comment]
This PR is superseded by: #42

**Pull request closed without merging**
